apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: ledger-api
    newName: ghcr.io/example/ledger-api
    newTag: sha-0000000
labels:
  - pairs:
      app.kubernetes.io/managed-by: argocd
    includeSelectors: false
