apiVersion: apps/v1
kind: Deployment
metadata:
  name: ledger-api
  namespace: payments
  labels:
    app: ledger-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ledger-api
  template:
    metadata:
      labels:
        app: ledger-api
    spec:
      containers:
        - name: ledger-api
          image: ledger-api:starter
          imagePullPolicy: IfNotPresent
          env:
            - name: PAYMENT_PROVIDER_MODE
              value: "sandbox"
            - name: LEDGER_DATABASE
              value: "local-dev"
          ports:
            - containerPort: 8080
