apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payments
resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - rbac.yaml
  - configmap.yaml
  - secret.enc.yaml
  - deployment-ledger.yaml
  - deployment-reporting.yaml
  - deployment-intruder.yaml
  - service-ledger.yaml
  - ingress.yaml
  - networkpolicy.yaml
