apiVersion: v1
kind: Secret
metadata:
    name: ledger-api-secrets
    namespace: payments
type: Opaque
stringData:
    STRIPE_API_KEY: ENC[AES256_GCM,data:TLHD22jNPH8ZaVC+jUu8jYZx,iv:kZ/M4pPqbhYb8cMmkNktcd1/r+3gY7RIrV7Hw472dig=,tag:kCYjIoNbO9+z1dNJ7g2fgQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:QuuKPX2KJCkR,iv:9fbZqgEWoXiuhf+jL3qtzMzYF7U4I6ldvithlerLY5s=,tag:QASN4CFxeEKDi676gngNow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVUhOL3p3b05RY3ZzdUVD
            UVhaUnZaeHNrai9Td3BxR05adCtwd216NkQwCmVlY09PQkthd0ZnV2JNZVVuMnNF
            VTNNZEdJMC9MWGZ3MmUxUkg3NXBBdUEKLS0tIGM5T2JkZm5zS3Q1MzdqcFpUY29s
            UXMrbXJBeEtFWGRpM05DY0tFNUJRSTQKMD5ZZsZ+oshDckCn1u7MuNrrZHM9CF9A
            hE1a3ADmaMidNUAt8Kx7uZFGF8uDuY0B8NU6EaJtbwhuvHC38tzMvw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1kylpwwm5dqh6k2xffycn5n5w8p9gk52cpuu92wafxzmedfw8zaesvdjzy0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-27T17:08:53Z"
    mac: ENC[AES256_GCM,data:yEzvmQGtJQoBajeEWwAdVWMn+2KnXq7q5rpnjfRe5/B6OsGef8lUQSPf91XfwTgMBXGlIyXg2Ma630ljs6Q+dMwARZLmz+6oBN/3y53nE4AHAFcfgRuQsZYIK5q4woLyS41fgnoLbinGDupva+A+H0oSqt/8Plc3Gwh7Jnr+WMs=,iv:YofnipDlw/XC+xU5eh3ft2YGRLA1NRftowAjW6uBGew=,tag:rT1PJXeMIFBOntzKir/JzA==,type:str]
    version: 3.13.3
