apiVersion: v1
kind: ServiceAccount
metadata:
  name: ledger-api
  namespace: payments
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reporting
  namespace: payments
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: intruder
  namespace: payments
automountServiceAccountToken: false
